// <auto-generated />
using System;
using InfrastructureRepository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InfrastructureRepository.Migrations
{
    [DbContext(typeof(RepositoryDbContext))]
    [Migration("20211202082432_userProfule")]
    partial class userProfule
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.UserProfile", b =>
                {
                    b.Property<int>("IdUserRef")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUserRef");

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("HospitalOnionArchitecture.Domain.Core.BaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BaseEntity");
                });

            modelBuilder.Entity("HospitalOnionArchitecture.Domain.Core.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BaseEntityId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BaseEntityId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.UserProfile", b =>
                {
                    b.HasOne("HospitalOnionArchitecture.Domain.Core.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("Domain.UserProfile", "IdUserRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HospitalOnionArchitecture.Domain.Core.User", b =>
                {
                    b.HasOne("HospitalOnionArchitecture.Domain.Core.BaseEntity", "BaseEntity")
                        .WithMany()
                        .HasForeignKey("BaseEntityId");

                    b.Navigation("BaseEntity");
                });

            modelBuilder.Entity("HospitalOnionArchitecture.Domain.Core.User", b =>
                {
                    b.Navigation("UserProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
